name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Update Pip
      run: python3 -m pip install --upgrade pip

    - name: Install regular and dev dependencies
      run: pip install .[dev]

    - name: Lint with flake8
      run: |
        flake8 oresat_tpane --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 oresat_tpane --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics

    - name: Run unit tests
      run: python3 -m unittest tests/spec_*.py
